**Question-1:** Create one hot encoding of an array. For example For an array([2, 3, 2, 2, 2, 1]) Output should be
   array([[ 0.,  1.,  0.],
             [ 0.,  0.,  1.],
             [ 0.,  1.,  0.],
             [ 0.,  1.,  0.],
             [ 0.,  1.,  0.],
            [ 1.,  0.,  0.]])

In [53]:
import numpy as np

#Creating a numpy array....
original_array = np.array([2, 3, 2, 2, 2, 1])

# Hot encoding array......
# First create an array that zeros's at every index...

encoded_array = np.zeros((len (original_array) , original_array.max()))

#Second arrange 1's over the mentioned 0's arrays....
temp = 0
for index in original_array:
  encoded_array[temp][index - 1] = 1
  temp = temp + 1


print(encoded_array)

[[0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]]


**Question-2:** Drop all missing values from an array Input: np.array([1,2,3,np.nan,5,6,7,np.nan]) Desired Output: array([ 1.,2.,3.,5.,6.,7.])

In [54]:
import numpy as np
import math

#Creating a numpy array....
numpy_array = np.array([1, 2 ,3, np.nan , 5 ,6, 7, np.nan])
another_array = []

for element in numpy_array:
  if math.isnan(element) != True:
    another_array.append(int(element))

print("While Using Simple Array Output is: ")
print(another_array)

#Using numpy method...

result = numpy_array[np.logical_not(np.isnan(numpy_array))]
print("Using Numpy Array Method...")
print(result)

While Using Simple Array Output is: 
[1, 2, 3, 5, 6, 7]
Using Numpy Array Method...
[1. 2. 3. 5. 6. 7.]


**Question-3:**  Find Local maxima from an array. Input: a = np.array([1, 3, 7, 1, 2, 6, 0, 1]) Desired Output: array([2, 5])

In [ ]:
import numpy as np

input_array = np.array([1, 3, 7, 1, 2, 6, 0, 1])

difference_array = np.diff(input_array)
indices_array = []

for element in range(len(difference_array)):
  if difference_array[element] < 0:
    indices_array.append(element)

print(indices_array)

[2, 5]


**Question-4:** From the given 1d array arr, generate a 2d matrix using strides,
For example for an array ([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])with a window length of w=4 and strides of s=2, like [[0,1,2,3], [2,3,4,5], [4,5,6,7]..]
w and s will be provided by user

In [ ]:
import numpy as np

window_length = int(input())
stride_length = int(input())
input_array = np.arange(15)

def generate_2d_matrix(input_array, wimdow_length , stride_length):

  #First calculate number of strides to be printed in output...
  number_of_strides = ((input_array.size - window_length) // stride_length) + 1

  return np.array( [ input_array [ stride: (stride + window_length) ] for stride in np.arange(0, number_of_strides * stride_length, stride_length) ] )

print(generate_2d_matrix(input_array , window_length , stride_length))

4
2
[[ 0  1  2  3]
 [ 2  3  4  5]
 [ 4  5  6  7]
 [ 6  7  8  9]
 [ 8  9 10 11]
 [10 11 12 13]]
